### ISSUE TITLE
Exception when getting hit with beige square

### ISSUE THREAD

**Issue by Scarsz** [MaxiMiniJaniJos/Squared#11]
```
Exception in thread "Thread-2" java.lang.NullPointerException
        at me.max.squared.BulletEnemyBullet.<init>(BulletEnemyBullet.java:27)
        at me.max.squared.BulletEnemy.tick(BulletEnemy.java:37)
        at me.max.squared.Handler.tick(Handler.java:19)
        at me.max.squared.Game.tick(Game.java:202)
        at me.max.squared.Game.run(Game.java:176)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by LemmoTresto** [comment]
Thanks for reporting, sorry for late response but I was busy with some stuff.

**Comment by LemmoTresto** [comment]
Fixed in next development build
